CREATE ROLE IF NOT EXISTS TEAMMATE_READER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TEAMMATE_READER;
GRANT USAGE ON DATABASE MSBA405 TO ROLE TEAMMATE_READER;
GRANT USAGE ON SCHEMA MSBA405.PROJECT TO ROLE TEAMMATE_READER;

GRANT SELECT ON ALL TABLES IN SCHEMA MSBA405.PROJECT TO ROLE TEAMMATE_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MSBA405.PROJECT TO ROLE TEAMMATE_READER;

GRANT ROLE TEAMMATE_READER TO USER teammate;

ALTER USER teammate SET
  DEFAULT_ROLE = TEAMMATE_READER,
  DEFAULT_WAREHOUSE = COMPUTE_WH,
  DEFAULT_NAMESPACE = 'MSBA405.PROJECT';
